# Generated by Django 5.0 on 2026-01-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='iimage',
            new_name='image',
        ),
    ]
